export default {
    FETCH_ANNOUNCEMENTS_REQUEST: 'FETCH_ANNOUNCEMENTS_REQUEST',
    FETCH_ANNOUNCEMENTS_SUCCESS: 'FETCH_ANNOUNCEMENTS_SUCCESS',
    FETCH_ANNOUNCEMENTS_ERROR: 'FETCH_ANNOUNCEMENTS_ERROR',

    FETCH_CONFIGURATION_REQUEST: 'FETCH_CONFIGURATION_REQUEST',
    FETCH_CONFIGURATION_SUCCESS: 'FETCH_CONFIGURATION_SUCCESS',
    FETCH_CONFIGURATION_ERROR: 'FETCH_CONFIGURATION_ERROR',

    FETCH_EVENTS_REQUEST: 'FETCH_EVENTS_REQUEST',
    FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
    FETCH_EVENTS_ERROR: 'FETCH_EVENTS_ERROR',

    FETCH_LOCATIONS_REQUEST: 'FETCH_LOCATIONS_REQUEST',
    FETCH_LOCATIONS_SUCCESS: 'FETCH_LOCATIONS_SUCCESS',
    FETCH_LOCATIONS_ERROR: 'FETCH_LOCATIONS_ERROR',
};